name: Deploy Node.js App to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "$EC2_SSH_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Add EC2 host to known hosts
        run: |
          ssh-keyscan -H 15.207.111.45 >> ~/.ssh/known_hosts

      - name: Deploy to EC2
        run: |
          ssh -v -o StrictHostKeyChecking=no ubuntu@15.207.111.45 << 'EOF'
            cd ~/apollo-filter-backend
            git pull origin main
            npm install
            pm2 restart all
          EOF
        env:
          EC2_SSH_KEY: ${{ secrets.EC2_SSH_KEY }}
